// <auto-generated />
using System;
using ERCore.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERCore.WebAPI.Migrations
{
    [DbContext(typeof(HeroContext))]
    partial class HeroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERCore.WebAPI.Model.Battle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtBegin")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("ERCore.WebAPI.Model.Heroe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("ERCore.WebAPI.Model.HeroeBattle", b =>
                {
                    b.Property<int>("heroeId")
                        .HasColumnType("int");

                    b.Property<int>("battleId")
                        .HasColumnType("int");

                    b.HasKey("heroeId", "battleId");

                    b.HasIndex("battleId");

                    b.ToTable("HeroBattles");
                });

            modelBuilder.Entity("ERCore.WebAPI.Model.SecretIdentity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("heroeId")
                        .HasColumnType("int");

                    b.Property<string>("realName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("heroeId")
                        .IsUnique();

                    b.ToTable("SecretIdentities");
                });

            modelBuilder.Entity("ERCore.WebAPI.Model.Weapon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("heroeId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("heroeId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("ERCore.WebAPI.Model.HeroeBattle", b =>
                {
                    b.HasOne("ERCore.WebAPI.Model.Battle", "battle")
                        .WithMany("HeroBattles")
                        .HasForeignKey("battleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERCore.WebAPI.Model.Heroe", "heroe")
                        .WithMany("heroBattles")
                        .HasForeignKey("heroeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERCore.WebAPI.Model.SecretIdentity", b =>
                {
                    b.HasOne("ERCore.WebAPI.Model.Heroe", "hero")
                        .WithOne("secretIdentity")
                        .HasForeignKey("ERCore.WebAPI.Model.SecretIdentity", "heroeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERCore.WebAPI.Model.Weapon", b =>
                {
                    b.HasOne("ERCore.WebAPI.Model.Heroe", "heroe")
                        .WithMany("weapons")
                        .HasForeignKey("heroeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
